### ISSUE TITLE
Viewer3d - Windows UI

### ISSUE THREAD

**Issue by FedeClaudi** [brainglobe/bgviewer#4]
The icons near the name are hard to see on windows, we should use custom images to have more homogeneous look across platforms. 

![image](https://user-images.githubusercontent.com/17436313/84952334-be03a580-b0e9-11ea-9590-6f90ac69e55d.png)

----
In general there's a few small diferrences between mac and windows (including brainrender's rendering being much higher quality on windows). @adamltyson  this is very low priority but when you have a change can you test stuff out on linux?

**Comment by vigji** [comment]
I also noticed lower quality on my macbook, do you know why that happens?

**Comment by FedeClaudi** [comment]
Have no idea, my guess is something to do with `vtk`, `brainrender` looks fine... 

In the latest version (`vtk 9.0.0`) the pyqt widget doesn't render at all (there's a hole in the app and you see the desktop behind), so maybe it's not supported anymore.  Maybe I can ask Marco Musy (creator of vedo) about it.

**Comment by adamltyson** [comment]
I'm getting this error when I try to run the 3d viewer, does something need updating?
```
  File "/home/adam/projects/bgviewer/bgviewer/viewer3d/ui.py", line 130, in __init__
    self.initUI()
  File "/home/adam/projects/bgviewer/bgviewer/viewer3d/ui.py", line 139, in initUI
    self.hierarchy = self.hierarchy_widget()
  File "/home/adam/projects/bgviewer/bgviewer/viewer3d/ui.py", line 203, in hierarchy_widget
    tree = self.atlas.hierarchy
AttributeError: 'ABA' object has no attribute 'hierarchy'
```
I'm on the current master of brainatlas-api & bgviewer.

**Comment by FedeClaudi** [comment]
This should fix it
```
pip install -U git+https://github.com/BrancoLab/BrainRender.git@brainglobeintegration
```


The viewer uses functionality from the dev branch of brainrender which supports integration with brainglobe.. I'm just waiting for brainglobe to come out to publish it

**Comment by adamltyson** [comment]
this is great, like really great.

I presume this sort of thing is going to work its way into brainrender?

Two small issues, which may be specific to ubuntu:
* How do you exit full screen mode? Escape works, but only if I haven't interacted with the brainrender window first
* The checkboxes are hard to see in dark mode (this might be because my OS in dark mode anyway?):

![Screenshot from 2020-06-18 10-47-37](https://user-images.githubusercontent.com/13147259/85005828-381b4500-b151-11ea-9a55-661816a0e209.png)

**Comment by FedeClaudi** [comment]
I might eventually make a GUI of some sort, but for this can stay as part of bgviewer, we need it for brainglobe anyways. 

> How do you exit full screen mode? Escape works, but only if I haven't interacted with the brainrender window first

Yeah, I need to figure it out...  I'll open an issue. You can catch a key press in brainrender, but not sure how to use this info to close the app... 

> The checkboxes are hard to see in dark mode (this might be because my OS in dark mode anyway?):

They look very different from both mac and windows. I think I will have to enforce a styling on them to avoid these issues. Bug the docs on checkboxes in QTrees are scarce. I can change their look but that seems to override how their look changes when ticked...

**Comment by FedeClaudi** [comment]
UI fixes to do:
- [x] tree item open/close images, different images for light and dark theme
- [x] check boxes styling 

Not windows specific:
- [x] add option to show axes to inspect atlas orientation/origin
- [x]  add option to use random colors for brain regions for atlases that don't come with colors

**Comment by FedeClaudi** [comment]
@vigji this is Marco's reply regarding the lower resolution: https://github.com/marcomusy/vedo/issues/161#issuecomment-645923063

**Comment by adamltyson** [comment]
Re lower resolution, this might be a stupid question, but is it a hardware thing? Are you testing on Windows desktops with dedicated GPUs, vs macbooks with integrated GPUs? It looks nice on ubuntu with an RTX2080, so maybe there's something throttling the resolution based on hardware.

**Comment by FedeClaudi** [comment]
sure, it may be related to that, but normal brainrender looks perfect on the mac as well so that makes me think that something else is causing it.

**Comment by FedeClaudi** [comment]
I've styled stuff: e0a17ebcdaf1b8c3084bfd03dd7984e41454810b

Now icons and tick boxes looks are specified by the images I've made.
Admittedly they could be better designed, but at least the code to use them is in place. 

----
I've added a couple other fixes and improvements, enjoy!

**Comment by vigji** [comment]
> @vigji this is Marco's reply regarding the lower resolution: [marcomusy/vedo#161 (comment)](https://github.com/marcomusy/vedo/issues/161#issuecomment-645923063)

Yeah it can definitively be an antialiasing thing...
