### ISSUE TITLE
BUG - Mouse atlas downloaded by default

### ISSUE THREAD

**Issue by vigji** [brainglobe/bgviewer#8]
Starting with a clear .brainglobe folder, even specifying the zebrafish atlas, bgviewer3D (or, I think BrainRender) downloads the Allen mouse one

**Comment by FedeClaudi** [comment]
thanks, will fix this (and maybe the other stuff... ) later today

**Comment by FedeClaudi** [comment]
The viewer was using the mouse atlas to create the hierarchy regardles of what was rendered, because of a bug. It's fixed now (will be sending a PR soon, so it won't download the mouse anymore)
