### ISSUE TITLE
Avoid multiple inheritance from Window and Scene

### ISSUE THREAD

**Issue by vigji** [brainglobe/bgviewer#9]
For readability I would temptatively suggest not to have multiple inheritance from two such unrelated classes, and maybe have one (logically I would say Window) containing reference to an instance of the other (I would say Scene), so it's clearer where methods come from

**Comment by FedeClaudi** [comment]
Sorry I'm not sure I get what you mean?
You're suggesting that `MainWindow` has something like `self.scene = Scene()` so that it's clear where the methods come from?

**Comment by vigji** [comment]
Yes exactly!

**Comment by FedeClaudi** [comment]
implemented here: d8fbd341b6b0fad414dbd9f3460ff243ea072d72
